version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  minhaapi:
    build: .
    container_name: minhaapi_container
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
